pipeline {

    agent {
        label 'docker-maven-trivy'
    }


    tools {
        maven 'Maven3'
        jdk 'JDK21'
    }

    environment {

        APP_NAME = "mini-account-management"

        IMAGE_NAME = "hareeshn903/atoz-app"

        IMAGE_TAG = "${BUILD_NUMBER}"

        DOCKER_CREDENTIALS_ID = "docker-cred"

        SONARQUBE_ENV = "sonar"

        KUBECONFIG = credentials('kubeconfig')
        GITHUB_PAT = credentials('GitHub-pat')

    }

    options {
        timestamps()
        disableConcurrentBuilds()
        buildDiscarder(logRotator(numToKeepStr: '10'))
    }

    stages {

        stage('Verify Tools') {
            steps {
                sh 'java -version'
                sh 'mvn -version'
                sh 'docker --version'
                sh 'trivy --version'
                sh 'helm version'
                sh 'kubectl version --client'
            }

            }
            
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                sh 'mvn clean package -DskipTests'
            }
        }

        stage('Unit Test') {
            steps {
                sh 'mvn test'
            }
        }

        stage('SonarQube Analysis') {
            steps {

                withSonarQubeEnv("${SONARQUBE_ENV}") {

                    sh """
                    mvn sonar:sonar \
                    -Dsonar.projectKey=${APP_NAME} \
                    -Dsonar.projectName=${APP_NAME}
                    """
                }
            }
        }

        stage('Docker Build') {
            steps {

                sh """
                docker build \
                -t ${IMAGE_NAME}:${IMAGE_TAG} \
                -t ${IMAGE_NAME}:latest .
                """
            }
        }

        stage('Trivy Scan') {
            steps {

                sh """
                trivy image \
                --exit-code 0 \
                --severity HIGH,CRITICAL \
                ${IMAGE_NAME}:${IMAGE_TAG}
                """
            }
        }

        stage('Docker Push') {
            steps {

                withDockerRegistry(
                    credentialsId: "${DOCKER_CREDENTIALS_ID}",
                    url: ""
                ) {

                    sh """
                    docker push ${IMAGE_NAME}:${IMAGE_TAG}
                    docker push ${IMAGE_NAME}:latest
                    """
                }
            }
        }

        // stage('Helm Lint') {
        //     steps {

        //         sh """
        //         helm lint helm/mini-account-management
        //         """
        //     }
        // }

        // stage('Helm Template Validation') {
        //     steps {

        //         sh """
        //         helm template mini-account-management \
        //         helm/mini-account-management > rendered.yaml
        //         """
        //     }
        // }

        // stage('Deploy To Kubernetes') {
        //     steps {

        //         sh """
        //         helm upgrade --install mini-account-management \
        //         helm/mini-account-management \
        //         --namespace siri \
        //         --create-namespace \
        //         --set image.repository=${IMAGE_NAME} \
        //         --set image.tag=${IMAGE_TAG}
        //         """
        //     }
        // }

        // stage('Verify Deployment') {
        //     steps {

        //         sh """
                
        //         kubectl rollout status deployment.apps/mini-account-management-mini-account-management -n siri
        //         """

        //         sh """
        //         kubectl get pods -n siri
        //         """
        //     }
        // }
        stage('Update GitOps Repository') {

    steps {

        withCredentials([
            usernamePassword(
                credentialsId: 'github-pat',
                usernameVariable: 'GIT_USER',
                passwordVariable: 'GIT_TOKEN'
            )
        ]) {

            sh '''

            echo "User=$GIT_USER"

            if [ -n "$GIT_TOKEN" ]; then
                echo "Token available"
            else
                echo "Token missing"
                    exit 1
            fi    

            rm -rf gitops

            git clone https://${GIT_USER}:${GIT_TOKEN}@github.com/hareeshn903/atoz-gitops.git gitops
            

            cd gitops
            echo "Before change:"
            grep -n "tag:" helm/mini-account-management/values.yaml

            sed -i 's/tag:.*/tag: "${IMAGE_TAG}"/' helm/mini-account-management/values.yaml
            echo "After:"
            grep -n "tag:" helm/mini-account-management/values.yaml

            cat helm/mini-account-management/values.yaml
            git diff

            git config user.email "hareeshn903@gmail.com"
            git config user.name "harijenkins"
            git add .
            git commit -m "Update image tag ${IMAGE_TAG}"
            git push
            '''
        }
    }
}
    }

   post {

    success {
        echo 'Pipeline completed successfully!'
    }

    failure {
        echo 'Pipeline failed!'
    }
}
}